FROM openjdk:17-oracle

ARG SPRING_PROFILE
ARG CORE_DATASOURCE_JDBC_URL
ARG CORE_DATASOURCE_USERNAME
ARG CORE_DATASOURCE_PASSWORD

ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILE}
ENV CORE_DATASOURCE_JDBC_URL ${CORE_DATASOURCE_JDBC_URL}
ENV CORE_DATASOURCE_USERNAME ${CORE_DATASOURCE_USERNAME}
ENV CORE_DATASOURCE_PASSWORD ${CORE_DATASOURCE_PASSWORD}

COPY api/build/libs/*.jar /sbooky.jar
ENTRYPOINT ["java", "-jar", "/sbooky.jar"]