FROM openjdk:17-oracle

ARG SPRING_PROFILE
ARG CORE_DATASOURCE_JDBC_URL
ARG CORE_DATASOURCE_USERNAME
ARG CORE_DATASOURCE_PASSWORD
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG JWT_KEY

ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILE}
ENV CORE_DATASOURCE_JDBC_URL ${CORE_DATASOURCE_JDBC_URL}
ENV CORE_DATASOURCE_USERNAME ${CORE_DATASOURCE_USERNAME}
ENV CORE_DATASOURCE_PASSWORD ${CORE_DATASOURCE_PASSWORD}
ENV KAKAO_CLIENT_ID ${KAKAO_CLIENT_ID}
ENV KAKAO_CLIENT_SECRET ${KAKAO_CLIENT_SECRET}
ENV JWT_KEY ${JWT_KEY}

COPY api/build/libs/*.jar /sbooky.jar
ENTRYPOINT ["java", "-jar", "/sbooky.jar"]
