services:
  sbooky-mysql:
    container_name: sbooky-mysql
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sbooky
      - MYSQL_DATABASE=sbooky
      - MYSQL_PASSWORD=sbooky
      - TZ=Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--lower_case_table_names=1",
      "--bind-address=0.0.0.0"
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    networks:
      - sbooky-network

  redis-master:
    container_name: sbooky-redis-master
    image: redis:8.2.0
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis/master/:/usr/local/etc/redis/
    networks:
      - sbooky-network

  redis-slave1:
    container_name: sbooky-redis-slave1
    image: redis:8.2.0
    ports:
      - "7001:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--replicaof", "sbooky-redis-master", "6379" ]
    volumes:
      - ./redis/slave/:/usr/local/etc/redis/
    depends_on:
      - redis-master
    networks:
      - sbooky-network

  redis-slave2:
    container_name: sbooky-redis-slave2
    image: redis:8.2.0
    ports:
      - "7002:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--replicaof", "sbooky-redis-master", "6379" ]
    volumes:
      - ./redis/slave/:/usr/local/etc/redis/
    depends_on:
      - redis-master
    networks:
      - sbooky-network

  redis-slave3:
    container_name: sbooky-redis-slave3
    image: redis:8.2.0
    ports:
      - "7003:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--replicaof", "sbooky-redis-master", "6379" ]
    volumes:
      - ./redis/slave/:/usr/local/etc/redis/
    depends_on:
      - redis-master
    networks:
      - sbooky-network

  redis-sentinel1:
    container_name: sbooky-redis-sentinel1
    image: redis:8.2.0
    command: [ "redis-server", "/usr/local/etc/redis/sentinel1.conf", "--sentinel" ]
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel1.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    networks:
      - sbooky-network

  redis-sentinel2:
    container_name: sbooky-redis-sentinel2
    image: redis:8.2.0
    command: [ "redis-server", "/usr/local/etc/redis/sentinel2.conf", "--sentinel" ]
    ports:
      - "26380:26380"
    volumes:
      - ./redis/sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel2.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    networks:
      - sbooky-network

  redis-sentinel3:
    container_name: sbooky-redis-sentinel3
    image: redis:8.2.0
    command: [ "redis-server", "/usr/local/etc/redis/sentinel3.conf", "--sentinel" ]
    ports:
      - "26381:26381"
    volumes:
      - ./redis/sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel3.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    networks:
      - sbooky-network

networks:
  sbooky-network:
    name: sbooky-network
    driver: bridge