spring.application.name: api
spring.profiles.active: local

spring:
  config:
    import:
      - "core.yml"
      - "swagger-yml"


---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

server:
  servlet:
    context-path: /dev

---
spring.config.activate.on-profile: prod

server:
  servlet:
    context-path: /prod

