# Circuit Breaker 설정 파일
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        slow-call-duration-threshold: 2000ms
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
    instances:
      REDIS_CACHE:
        base-config: default
        record-exceptions:
          - com.dnd.sbooky.api.support.cache.exception.CacheException
          - io.lettuce.core.RedisException
          - io.lettuce.core.RedisConnectionException
          - io.lettuce.core.RedisCommandTimeoutException
          - org.springframework.data.redis.RedisConnectionFailureException
      RATE_LIMITER:
        base-config: default
        record-exceptions:
          - io.lettuce.core.RedisException
          - io.lettuce.core.RedisConnectionException
          - io.lettuce.core.RedisCommandTimeoutException
          - org.springframework.data.redis.RedisConnectionFailureException




---
spring.config.activate.on-profile: local

logging:
  level:
    io.github.resilience4j: INFO

---
spring.config.activate.on-profile: dev

resilience4j:
  circuitbreaker:
    instances:
      REDIS_CACHE:
        failure-rate-threshold: 40
      RATE_LIMITER:
        failure-rate-threshold: 40
logging:
  level:
    io.github.resilience4j: INFO

---
spring.config.activate.on-profile: prod

resilience4j:
  circuitbreaker:
    instances:
      REDIS_CACHE:
        wait-duration-in-open-state: 60s
      RATE_LIMITER:
        wait-duration-in-open-state: 60s

logging:
  level:
    io.github.resilience4j: WARN
