CREATE USER IF NOT EXISTS 'sbooky'@'%' IDENTIFIED BY 'sbooky';

GRANT ALL PRIVILEGES ON *.* TO 'sbooky'@'%';

CREATE DATABASE IF NOT EXISTS sbooky DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
