spring:
  jpa:
    hibernate:
      ddl-auto: validate

core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring.config.activate.on-profile: local

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
    password: 1234

logging:
  level:
    org:
      springframework:
        jdbc: debug
core:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/sbooky?serverTimezone=Asia/Seoul
    username: sbooky
    password: sbooky

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: prod
