spring:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      repositories:
        enabled: false

core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    sentinel:
      master: mymaster
      nodes:
        - host: redis-sentinel1
          port: 26379
        - host: redis-sentinel2
          port: 26380
        - host: redis-sentinel3
          port: 26381
    password: 1234

logging:
  level:
    org:
      springframework:
        jdbc: debug
core:
  datasource:
    jdbc-url: jdbc:mysql://sbooky-mysql:3306/sbooky?serverTimezone=Asia/Seoul
    username: sbooky
    password: sbooky

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    sentinel:
      master: ${REDIS_SENTINEL_MASTER_NAME}
      nodes:
        - ${REDIS_SENTINEL_1}
        - ${REDIS_SENTINEL_2}
        - ${REDIS_SENTINEL_3}
    password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: prod
